-- Script SQL para ser executado no SQL Editor do Supabase (supabase.com)

-- 1. Criação da tabela de transações
CREATE TABLE IF NOT EXISTS transacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL CHECK(tipo IN ('receita', 'despesa')),
    valor NUMERIC(12, 2) NOT NULL CHECK(valor > 0),
    descricao TEXT NOT NULL,
    categoria TEXT NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Índice para consultas rápidas por data e categoria
CREATE INDEX IF NOT EXISTS idx_transacoes_data ON transacoes(data DESC);
CREATE INDEX IF NOT EXISTS idx_transacoes_tipo ON transacoes(tipo);

-- 3. Exemplo de inserção inicial de dados (opcional)
INSERT INTO transacoes (tipo, valor, descricao, categoria, data)
VALUES 
    ('receita', 5000.00, 'Salário Mensal', 'Salário', CURRENT_DATE - INTERVAL '5 days'),
    ('despesa', 150.00, 'Supermercado', 'Alimentação', CURRENT_DATE - INTERVAL '3 days'),
    ('despesa', 89.90, 'Assinatura Internet', 'Moradia', CURRENT_DATE - INTERVAL '1 day');

-- 4. Liberação de leitura e escrita anônima (ou configure RLS se preferir autenticação)
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura para todos" 
ON transacoes FOR SELECT USING (true);

CREATE POLICY "Permitir inserção para todos" 
ON transacoes FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir exclusão para todos" 
ON transacoes FOR DELETE USING (true);
